"""Add status column to events table

Revision ID: 1fc89378b619
Revises: 9eff92c9122f
Create Date: 2025-09-09 15:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc89378b619'
down_revision = '9eff92c9122f' # Make sure this matches the 'Revises' ID above
branch_labels = None
depends_on = None

# Define the ENUM type for use in the migration
event_status_enum = sa.Enum('ACTIVE', 'CANCELLED', name='eventstatus')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, create the ENUM type in the database
    event_status_enum.create(op.get_bind())
    
    # Then, add the column that uses this new type
    op.add_column('events', sa.Column('status', event_status_enum, nullable=False, server_default='ACTIVE'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, drop the column
    op.drop_column('events', 'status')
    
    # Then, drop the ENUM type from the database
    event_status_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###